name = "potion-tracker-pro"
compatibility_date = "2024-02-20"

# Configure Cloudflare Pages
[pages]
root = "dist"

# Enable SPA mode for client-side routing
[[pages.rules]]
type = "NavigationFallback"
navigation_fallback = "/index.html"